# Project
version=0.4.1
group=me.basiqueevangelist
java_version=21

# Common
minecraft_version=1.21.1
mod_name=FlashFreeze
mod_author=BasiqueEvangelist
mod_id=flashfreeze
license=LGPL-3.0-only
credits=
description=Keep unknown blocks and items
minecraft_version_range=[1.21.1, 1.21.2)
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric
fabric_version=0.115.1+1.21.1
fabric_loader_version=0.16.10

# NeoForge
neoforge_version=21.1.128
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
lithium_version=mc1.21.1-0.14.8