# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=1.21.1
	loader_version=0.16.10

# Mod Properties
	mod_version = 0.4.0
	maven_group = me.basiqueevangelist
	archives_base_name = flashfreeze

# Dependencies
	fabric_api_version=0.115.1+1.21.1
	lithium_version=mc1.21.1-0.14.8-fabric
	cca_version=6.1.2
	modmenu_version=11.0.3
	polymer_version=0.9.18+1.21.1
